module.exports={
    PRODUCT_COLLECTIONS:'product',
    USER_COLLECTIONS:'user',
    CART_COLLECTIONS:'cart',
    ORDER_COLLECTIONS:'order',
    ADMIN_COLLECTIONS:'admin',
    CATEGORY_COLLECTIONS:'category',
    USER_MESSAGES:'userMsg',
    WISHLIST_COLLECTIONS:'wishlist',
    OTP_COLLECTION:'otp'
}